version: '3'
services:
  web:
    container_name: apollo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'url=https://github.com/MarvinVoV/apollo.git'
        - 'project=apollo'
        - 'artifactId=web-boot'
        - 'version=0.0.1-SNAPSHOT-exec'
    depends_on:
      - db
      - redis
    ports:
      - ${APP_PORT}:8081
    volumes:
      - '.:/code'
      - 'log_volume01:/var/log'
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - 'redis_data:/data'
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SECRET}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_SECRET}
volumes:
  log_volume01:
  redis_data:
  db_data: