version: '3'
services:
  web:
    container_name: apollo
    image: marvinvov/apollo:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
    volumes:
      - .:/code
      - 'web_service_log:/var/log'
    links:
      - db:docker-mysql
      - redis:docker-redis
  redis:
    image: redis:alpine
    ports:
      - "6376:6379"
    volumes:
      - "redis_data:/data"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3303:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apollo
volumes:
  web_service_log:
  redis_data:
  db_data: