spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apollo?createDatabaseIfNotExist=true
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    username: root
    password: superman
    initialization-mode: always
  redis:
    port: 6379
    password:
    host: localhost
  session:
    redis:
      namespace: "spring:session"
      flush-mode: on_save
    store-type: redis
logging:
  level:
    org:
      springframework:
        web: info
        boot:
          autoconfigure:
            security: info
        security: info
    org.mybatis: debug
    marvin.apollo.common.dal.mybatis: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: "count=countSql"
  offset-as-page-num: true
mybatis:
  config-location: "classpath:mybatis-config.xml"
  mapper-locations: "classpath:mapper/*.xml"

server:
  port: 8081
  servlet:
    session:
      timeout: 300