spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/apollo?createDatabaseIfNotExist=true
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    username: root
    password: root
    initialization-mode: always
  redis:
    port: 6379
    password:
    host: docker-redis
  session:
    redis:
      namespace: "spring:session"
      flush-mode: on_save
    store-type: redis
logging:
  level:
    org.springframework.web: info
    org.mybatis: info
    marvin.apollo.common.dal.mybatis: info
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: "count=countSql"
  offset-as-page-num: true
mybatis:
  config-location: "classpath:mybatis-config.xml"
  mapper-locations: "classpath:mapper/*.xml"

server:
  port: 8081
  servlet:
    session:
      timeout: 300